# Generated by Django 4.1.5 on 2023-03-22 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=45)),
                ('vigencia_departamento', models.CharField(max_length=80)),
                ('fecha_anulacion_departamento', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hw',
            fields=[
                ('id_hw', models.AutoField(primary_key=True, serialize=False)),
                ('ip_hw', models.CharField(max_length=45)),
                ('url_hw', models.CharField(blank=True, max_length=45, null=True)),
                ('user_hw', models.CharField(max_length=45)),
                ('password_hw', models.CharField(max_length=45)),
                ('puerto_hw', models.CharField(max_length=45)),
                ('direccion_fisica', models.CharField(max_length=45)),
                ('vigencia_hw', models.CharField(max_length=80)),
                ('fecha_anulacion_hw', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hw',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id_ip', models.AutoField(primary_key=True, serialize=False)),
                ('id_hw', models.IntegerField(blank=True, null=True)),
                ('ip', models.CharField(max_length=45)),
                ('puerto', models.CharField(blank=True, max_length=45, null=True)),
                ('vigencia_sistema', models.CharField(max_length=80)),
                ('fecha_anulacion_sistema', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_modulo', models.CharField(max_length=45)),
                ('vigencia_modulo', models.CharField(max_length=80)),
                ('fecha_anulacion_modulo', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id_plataforma', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plataforma', models.CharField(max_length=45)),
                ('tipo_ambiente_plataforma', models.CharField(max_length=45)),
                ('tipo_servidor_plataforma', models.CharField(max_length=45)),
                ('vigencia_plataforma', models.CharField(max_length=45)),
                ('fecha_anulacion_plataforma', models.DateField(blank=True, null=True)),
                ('tipo_motor_bd', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre_esquema_bd', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre_instancia_bd', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'plataforma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id_responsable', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_responsable', models.CharField(blank=True, max_length=45, null=True)),
                ('vigencia_responsable', models.CharField(max_length=80)),
                ('fecha_anulacion_responsable', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'responsable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id_sistema', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sistema', models.CharField(max_length=45)),
                ('vigencia_sistema', models.CharField(max_length=80)),
                ('fecha_anulacion_sistema', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sistema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Submodulo',
            fields=[
                ('id_submodulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_submodulo', models.CharField(max_length=45)),
                ('vigencia_submodulo', models.CharField(max_length=80)),
                ('fecha_anulacion_submodulo', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'submodulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sw',
            fields=[
                ('id_sw', models.AutoField(primary_key=True, serialize=False)),
                ('endpoint_sw', models.CharField(blank=True, max_length=45, null=True)),
                ('tipo_sw', models.CharField(blank=True, max_length=45, null=True)),
                ('url_sw', models.CharField(blank=True, max_length=45, null=True)),
                ('user_sw', models.CharField(blank=True, max_length=45, null=True)),
                ('password_sw', models.CharField(blank=True, max_length=45, null=True)),
                ('vigencia_sw', models.CharField(blank=True, max_length=80, null=True)),
                ('fecha_anulacion_hw', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sw',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResponsableSistema',
            fields=[
                ('id_responsable', models.OneToOneField(db_column='id_responsable', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='environment_app.responsable')),
            ],
            options={
                'db_table': 'responsable_sistema',
                'managed': False,
            },
        ),
    ]
